# bashrc for Ubuntu VM - Carl Unsworth
# --------------------------------------

export DOTFILESDIR="/home/cu/Scripts/DotFiles/"

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=5000
HISTFILESIZE=5000
HISTTIMEFORMAT='%F %T '  # inlcudes time as well as command and num in history output

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Use liquidprompt
source /home/cu/Packages/liquidprompt/liquidprompt

# aliases
alias ls='ls --color=auto' # this here rather than in 'bash_aliases' as OSX doesn't like this option
if [ -f $DOTFILESDIR/bash_aliases ]; then
    source $DOTFILESDIR/bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# added by carl 7Oct14 for less syntaxt highlighting.
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R '

# added by carl for ssh key managemment
eval `keychain --eval id_rsa_macbook`
