# bash_profile for MacBook.  Carl Unsworth

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=5000
HISTFILESIZE=5000
HISTTIMEFORMAT='%F %T '  # inlcudes time as well as command and num in history output

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# attempt at proper bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# attempt to get less source highlighting working
export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"     
export LESS=' -R '

# Custom bash prompt via kirsle.net/wizards/ps1.html
#export PS1="\[$(tput bold)\]\[$(tput setaf 4)\][\[$(tput setaf 2)\]\u\[$(tput setaf 4)\]@\[$(tput setaf 2)\]\h \[$(tput setaf 2)\]\W\[$(tput setaf 4)\]]\\$ \[$(tput sgr0)\]"
# Trying out liquidprompt
source /Users/cu/Packages/liquidprompt/liquidprompt

# attempt at colour output
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# load aliases
source /Users/cu/Scripts/DotFiles/MacBookPro/bash_aliases

# set up ssh-agent
#eval `ssh-agent`

# set up git tab completion
source /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-completion.bash
