# bash_profile for MacBook.  Carl Unsworth
#------------------------------------------

export DOTFILESDIR="/Users/carlunsworth/Scripts/DotFiles/"

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=10000
HISTTIMEFORMAT='%F %T '  # inlcudes time as well as command and num in history output

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# attempt at proper bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# set up git tab completion
source /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-completion.bash

# Get less source highlighting working using gtk source highlighting library
export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"     
export LESS=' -R '

# Trying out liquidprompt instead as of Feb 2015, replaces PS1 redefine below
# Only load Liquid Prompt in interactive shells, not from a script or from scp
[[ $- = *i* ]] && source ~/Packages/liquidprompt/liquidprompt

# Custom bash prompt via kirsle.net/wizards/ps1.html
# export PS1="\[$(tput bold)\]\[$(tput setaf 4)\][\[$(tput setaf 2)\]\u\[$(tput setaf 4)\]@\[$(tput setaf 2)\]\h \[$(tput setaf 2)\]\W\[$(tput setaf 4)\]]\\$ \[$(tput sgr0)\]"

# attempt at colour output
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# load aliases
source $DOTFILESDIR/bash_aliases

# set up ssh-agent
# not needed on MacBook.  Implemented using OS X keyring and ssh-add.

# Cheat color
export CHEATCOLORS=true

# Nano for default editor
export EDITOR=nano

# Add Scritps to PATH
export PATH=$PATH:/Users/carlunsworth/Scripts/OSX_PathScripts/

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
