# Carl Unsworth Bash profile for Daresbury Lab Nuclear Group Network

# Track which startup files have been sourced.
# Stops me having to keep looking up which files are sourced when
# Also useful to add similar line to other home and /etc/startup scripts
export SOURCEDSCRIPTS=$SOURCEDSCRIPTS:.bash_profile

# source bashrc if it exists. Other config is in there
[[ -r ~/.bashrc ]] && . ~/.bashrc
